<?php

namespace app\models;

use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;

class TransactionSearch extends Transaction implements SearchInterface
{

    public function rules(): array
    {
        return [
            [['id', 'transaction_id', 'reference', 'phone','callback_data', 'amount', 'currency', 'payment_status', 'status', 'updated_at', 'type', 'created_at', 'description'], 'safe'],
        ];
    }

    public function search($params = null)
    {
        Yii::$app->session->remove("data");
        $query = $this->ql();
        if ($params) {
            $this->load($params);
        }


        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 15,
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ],
                'attributes' => [
                    'id',
                ],
            ],
        ]);

        if (!$this->validate()) {
            return $dataProvider;
        }
        if (!empty($params['TransactionSearch'])) {
            $query->andFilterWhere(['id' => $this->id]);
            $query->andFilterWhere(['phone' => $this->phone]);
            $query->andFilterWhere(['type' => $this->type]);
            $query->andFilterWhere(['currency' => $this->currency]);
        }


        return $dataProvider;


    }

    public function ql()
    {
        return (new Query())->select(['*'])->from('transaction');
    }

    public function searchFields()
    {
        return [
            'id' => [
                'type' => 'text',
                'placeholder' => 'Search by ID',
                'name' => 'id',
            ],
            'phone' => [
                'type' => 'text',
                'placeholder' => 'Search by phone number',
                'name' => 'phone',
            ],
            'transaction_id' => [
                'type' => 'text',
                'placeholder' => 'Search by Txn no',
                'name' => 'transaction_id',
            ]
        ];
    }

    public function getData()
    {
        return Yii::$app->session->get("data") ?? $this->ql()->all();
    }

    public function ExportColumns()
    {
        return [
            'id' => 'ID',
            'transaction_id' => 'Txn.No',
            'phone' => 'Phone',
            'amount' => 'Amount',
            'description' => 'Description',
            'callback_data'=>'Callback Data',
            'payment_status' => 'Payment Status',
            'status' => 'Status',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
            'type' => 'Type',
            'reference' => 'Reference',

        ];
    }

    public function tableColumns()
    {
        return [
            'transaction_id' => 'Txn.No',
            'phone' => 'Phone',
            'amount' => ['label' => 'Amount', 'format' => function ($value) {
                return $value ? 'UGX ' . number_format($value) : '';
            }],
//            'currency' => 'Currency',
            'type' => 'Type',
//            'description' => ['label' => 'Description',
//                'format' => function ($value) {
//                    if (!$value) {
//                        return '';
//                    }
//
//                    if (strlen($value) <= 140) {
//                        return $value;
//                    }
//
//                    return substr($value, 0, 137) . '...';
//                }
//            ],
            'payment_status' => 'Payment Status',
            'status' => 'Status',
            'message' => 'Message',
            'updated_at' => [
                'label' => 'Settlement Date',
                'format' => function ($value) {
                    return $value ? Yii::$app->formatter->asDate($value, 'php:Y-m-d') : '';
                }
            ],
        ];
    }

    public function scenarios()
    {
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }
}
